# Generated by Django 4.2.6 on 2023-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=1000)),
                ('producer', models.CharField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('length', models.IntegerField()),
            ],
        ),
    ]
