name: Java CI with Maven and Selenium

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - uses: browser-actions/setup-firefox@latest
    - run: firefox --version
    
    - name: Build and test with Maven
      # run: mvn -B package --file pom.xml
      run: mvn clean package

    - name: The job has failed
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
        OrganizationName: "mwo5piotr"
        PAT: "PAT"
        ProjectName: "mwo5"
        AreaPath: "mwo5"
        IterationPath: "mwo5"
        GithubToken: "GithubToken"
        WorkflowFileName: "pipeline.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.GITHUBTOKEN}}
